
doctrine:
    dbal:
        default_connection: es
        connections:
            es:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "es"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            it:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "it"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

    orm:
        default_entity_manager: es
        entity_managers:
            default:
                connection: es
                mappings:
                    AppBundle: ~
            es:
                connection: es
                mappings:
                    AppBundle: ~

            it:
                connection: it
                mappings:
                    AppBundle: ~