services:
    entity.manager.service:
        class: AppBundle\Service\EntityManagerService
        arguments:
          - '@doctrine'
          - '@session'

    app.repository.task:
        class: AppBundle\Service\EntityManagerService
        factory: ['@entity.manager.service', getRepository]
        arguments: ['AppBundle:Task']